name: CI/CD Pipeline

# Kiedy uruchomić:
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Pobierz kod z repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Skonfiguruj Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Maven dependencies dla szybszego buildu
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Kompiluj projekt
      - name: Compile with Maven
        run: mvn clean compile

      # Uruchom testy z pełnym reportem
      - name: Run tests
        run: mvn clean test

      # Sprawdź czy pliki testów istnieją
      - name: Check test reports
        run: |
          echo "Checking for test report files..."
          find . -name "*.xml" -path "*/surefire-reports/*" -type f || echo "No XML files found"
          ls -la target/surefire-reports/ || echo "No surefire-reports directory"

      # Upload wyników testów (tylko jeśli istnieją)
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always() && hashFiles('target/surefire-reports/*.xml') != ''
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false